name: Clear cache

on:
  schedule:
  - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  clear-cache:
    name: Clear cache
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
    - name: Clear all cache
      run: gh cache delete -a
      env:
        GH_TOKEN: ${{ github.token }}
